# Generated by Django 3.2.16 on 2022-10-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
